# Generated by Django 5.2.8 on 2025-11-12 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default=1, help_text='min: 4, max: 7. ex: #0000ff', max_length=7, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Button text color'),
            preserve_default=False,
        ),
    ]
