# Generated by Django 5.2.8 on 2025-11-12 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_button_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Romanian title')),
                ('sub_title_en', models.CharField(help_text='min: 10, max: 50', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='English sub title')),
                ('sub_title_ro', models.CharField(help_text='min: 10, max: 50', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Romanian sub title')),
                ('image', models.ImageField(help_text='accepted formats: jpg, webp', upload_to='banners/', verbose_name='Image')),
                ('text_color', models.CharField(help_text='min: 4, max: 7. ex: #0000ff', max_length=7, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Text color')),
                ('button_color', models.CharField(help_text='min: 4, max: 7. ex: #0000ff', max_length=7, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Button color')),
                ('button_text_color', models.CharField(help_text='min: 4, max: 7. ex: #0000ff', max_length=7, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Button text color')),
                ('order', models.PositiveIntegerField(verbose_name='Order number')),
            ],
            options={
                'verbose_name': 'sub-banner',
                'verbose_name_plural': 'sub-banners',
                'db_table': 'sub_banners',
            },
        ),
    ]
