"""dsda

Revision ID: 01582c439a78
Revises: 31495baebde3
Create Date: 2025-08-06 17:09:59.082097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01582c439a78'
down_revision: Union[str, Sequence[str], None] = '31495baebde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug_en', sa.String(), nullable=True))
    op.add_column('products', sa.Column('slug_ro', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['name_ro'])
    op.create_unique_constraint(None, 'products', ['slug_en'])
    op.create_unique_constraint(None, 'products', ['name_en'])
    op.create_unique_constraint(None, 'products', ['slug_ro'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'slug_ro')
    op.drop_column('products', 'slug_en')
    # ### end Alembic commands ###
