"""dsda

Revision ID: 0be65637da3f
Revises: bf1d9d8ba2df
Create Date: 2025-08-14 23:52:47.090298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0be65637da3f"
down_revision: Union[str, Sequence[str], None] = "bf1d9d8ba2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("category_translations_category_id_fkey"),
        "category_translations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "category_translations",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category_translations", type_="foreignkey")
    op.create_foreign_key(
        op.f("category_translations_category_id_fkey"),
        "category_translations",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
