"""dsda

Revision ID: 0cc648dd74fa
Revises: 3d7cf9cf7227
Create Date: 2025-08-05 16:52:16.863482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc648dd74fa'
down_revision: Union[str, Sequence[str], None] = '3d7cf9cf7227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description_en', sa.String(), nullable=False))
    op.add_column('products', sa.Column('description_ro', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_ro')
    op.drop_column('products', 'description_en')
    # ### end Alembic commands ###
