"""dsda

Revision ID: 12b38632862c
Revises: 0be65637da3f
Create Date: 2025-08-15 03:28:06.968701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12b38632862c"
down_revision: Union[str, Sequence[str], None] = "0be65637da3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("language_codes", sa.Column("name", sa.String(), nullable=True))
    op.create_unique_constraint(None, "language_codes", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "language_codes", type_="unique")
    op.drop_column("language_codes", "name")
    # ### end Alembic commands ###
