"""dsda

Revision ID: 130e664f9c6d
Revises: 3769297142d0
Create Date: 2025-08-14 19:05:02.996160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "130e664f9c6d"
down_revision: Union[str, Sequence[str], None] = "3769297142d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_variant_specifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_variant_id", sa.Integer(), nullable=False),
        sa.Column("specification_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specification_type_id"],
            ["product_specification_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_variant_specific_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("product_variant_specification_id", sa.Integer(), nullable=False),
        sa.Column("language_code_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_code_id"],
            ["language_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_specification_id"],
            ["product_variant_specifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_variant_specific_translations")
    op.drop_table("product_variant_specifications")
    # ### end Alembic commands ###
