"""dsda

Revision ID: 15b5b4d44069
Revises: c88915175785
Create Date: 2025-08-14 16:28:41.831801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b5b4d44069'
down_revision: Union[str, Sequence[str], None] = 'c88915175785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_specification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_specification_type_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_specification_type_id', sa.Integer(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.ForeignKeyConstraint(['product_specification_type_id'], ['product_specification_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specification_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specification_type_id'], ['product_specification_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_specifications')
    op.drop_table('product_specification_type_translations')
    op.drop_table('product_specification_types')
    # ### end Alembic commands ###
