"""dsda

Revision ID: 1fcb7cdda874
Revises: 
Create Date: 2025-08-10 22:47:52.964518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcb7cdda874'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
