"""dsda

Revision ID: 247e92b810b1
Revises: 12b38632862c
Create Date: 2025-08-15 03:28:57.604174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "247e92b810b1"
down_revision: Union[str, Sequence[str], None] = "12b38632862c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "language_codes", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("language_codes", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
