"""dsda

Revision ID: 31495baebde3
Revises: efb9eca91ba3
Create Date: 2025-08-06 16:35:40.162653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31495baebde3'
down_revision: Union[str, Sequence[str], None] = 'efb9eca91ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('new_products_count', name='conftype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conf')
    # ### end Alembic commands ###
