"""dsda

Revision ID: 3b87b8ad897d
Revises: 456168d8be14
Create Date: 2025-08-14 14:44:38.755501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b87b8ad897d"
down_revision: Union[str, Sequence[str], None] = "456168d8be14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_translation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.drop_constraint(op.f("products_name_en_key"), "products", type_="unique")
    op.drop_constraint(op.f("products_name_ro_key"), "products", type_="unique")
    op.drop_constraint(op.f("products_slug_en_key"), "products", type_="unique")
    op.drop_constraint(op.f("products_slug_ro_key"), "products", type_="unique")
    op.drop_column("products", "name_en")
    op.drop_column("products", "description_en")
    op.drop_column("products", "name_ro")
    op.drop_column("products", "slug_en")
    op.drop_column("products", "slug_ro")
    op.drop_column("products", "description_ro")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("description_ro", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("slug_ro", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("slug_en", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("name_ro", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("description_en", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("name_en", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("products_slug_ro_key"),
        "products",
        ["slug_ro"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("products_slug_en_key"),
        "products",
        ["slug_en"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("products_name_ro_key"),
        "products",
        ["name_ro"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("products_name_en_key"),
        "products",
        ["name_en"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("product_translation")
    op.drop_table("language_codes")
    # ### end Alembic commands ###
