"""dsda

Revision ID: 435edf186c2b
Revises: b4895f94ab9f
Create Date: 2025-08-14 21:58:00.343013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "435edf186c2b"
down_revision: Union[str, Sequence[str], None] = "b4895f94ab9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_product_likes_product_id_fkey"),
        "user_product_likes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("user_product_likes_user_id_fkey"),
        "user_product_likes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_product_likes",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "user_product_likes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_product_likes", type_="foreignkey")
    op.drop_constraint(None, "user_product_likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_product_likes_user_id_fkey"),
        "user_product_likes",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("user_product_likes_product_id_fkey"),
        "user_product_likes",
        "products",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###
