"""dsda

Revision ID: 47cf61189007
Revises: 435edf186c2b
Create Date: 2025-08-14 22:53:07.941772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47cf61189007"
down_revision: Union[str, Sequence[str], None] = "435edf186c2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_codes", sa.Column("is_default", sa.Boolean(), nullable=True)
    )
    op.create_unique_constraint(None, "language_codes", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "language_codes", type_="unique")
    op.drop_column("language_codes", "is_default")
    # ### end Alembic commands ###
