"""dsda

Revision ID: 672a873b1521
Revises: 79d2591b4cb7
Create Date: 2025-08-06 15:35:13.542566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672a873b1521'
down_revision: Union[str, Sequence[str], None] = '79d2591b4cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug_en', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('slug_ro', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'slug_ro')
    op.drop_column('categories', 'slug_en')
    # ### end Alembic commands ###
