"""dsda

Revision ID: 73845605ee48
Revises: b1e1bcd01a5d
Create Date: 2025-08-14 20:22:32.141485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73845605ee48"
down_revision: Union[str, Sequence[str], None] = "b1e1bcd01a5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "product_variant_specifications",
        "product_variants",
        ["product_variant_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_variant_specifications", type_="foreignkey")
    # ### end Alembic commands ###
