"""dsda

Revision ID: 87eb701ac61c
Revises: b3fbddd7c7f3
Create Date: 2025-08-06 20:35:15.449023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eb701ac61c'
down_revision: Union[str, Sequence[str], None] = 'b3fbddd7c7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'slug_ro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'slug_ro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'slug_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
