"""dsda

Revision ID: 8e877331b75f
Revises: e73c59dfebee
Create Date: 2025-08-14 17:01:31.206902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e877331b75f'
down_revision: Union[str, Sequence[str], None] = 'e73c59dfebee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant_type_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_variant_type_id', sa.Integer(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.ForeignKeyConstraint(['product_variant_type_id'], ['product_variant_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_type_id'], ['product_variant_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant_translations')
    op.drop_table('product_variants')
    op.drop_table('product_variant_type_translations')
    op.drop_table('product_variant_types')
    # ### end Alembic commands ###
