"""dsda

Revision ID: 94af0035f227
Revises: e5d64df4450e
Create Date: 2025-08-18 02:35:47.541156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94af0035f227'
down_revision: Union[str, Sequence[str], None] = 'e5d64df4450e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_top',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_top',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
