"""dsda

Revision ID: a1b9f2ee898e
Revises: 130e664f9c6d
Create Date: 2025-08-14 20:10:45.826999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b9f2ee898e"
down_revision: Union[str, Sequence[str], None] = "130e664f9c6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("category_translations_category_id_key"),
        "category_translations",
        type_="unique",
    )
    op.create_foreign_key(
        None, "category_translations", "categories", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category_translations", type_="foreignkey")
    op.create_unique_constraint(
        op.f("category_translations_category_id_key"),
        "category_translations",
        ["category_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
