"""dsda

Revision ID: b1e1bcd01a5d
Revises: a1b9f2ee898e
Create Date: 2025-08-14 20:12:29.706769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e1bcd01a5d'
down_revision: Union[str, Sequence[str], None] = 'a1b9f2ee898e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product_specifications', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_specifications', type_='foreignkey')
    # ### end Alembic commands ###
