"""dsda

Revision ID: b33385f0525f
Revises: 8330b043ce3e
Create Date: 2025-08-14 21:48:41.507302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33385f0525f'
down_revision: Union[str, Sequence[str], None] = '8330b043ce3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_extra_images_product_id_fkey'), 'product_extra_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_extra_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_extra_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_extra_images_product_id_fkey'), 'product_extra_images', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
