"""dsda

Revision ID: bf1d9d8ba2df
Revises: 47cf61189007
Create Date: 2025-08-14 22:53:54.671983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1d9d8ba2df'
down_revision: Union[str, Sequence[str], None] = '47cf61189007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_codes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_codes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
