"""dsda

Revision ID: c0a34a56f33c
Revises: 95327ee9b475
Create Date: 2025-08-17 20:15:18.327442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0a34a56f33c"
down_revision: Union[str, Sequence[str], None] = "95327ee9b475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("main_image", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_1", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_2", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_3", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_4", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_5", sa.String(), nullable=True))
    op.add_column("products", sa.Column("extra_image_6", sa.String(), nullable=True))
    op.drop_column("products", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("products", "extra_image_6")
    op.drop_column("products", "extra_image_5")
    op.drop_column("products", "extra_image_4")
    op.drop_column("products", "extra_image_3")
    op.drop_column("products", "extra_image_2")
    op.drop_column("products", "extra_image_1")
    op.drop_column("products", "main_image")
    # ### end Alembic commands ###
