"""dsda

Revision ID: c88915175785
Revises: 281164222fa0
Create Date: 2025-08-14 15:50:34.826702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88915175785'
down_revision: Union[str, Sequence[str], None] = '281164222fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_constraint(op.f('categories_name_en_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_name_ro_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_slug_en_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_slug_ro_key'), 'categories', type_='unique')
    op.drop_column('categories', 'slug_ro')
    op.drop_column('categories', 'name_en')
    op.drop_column('categories', 'name_ro')
    op.drop_column('categories', 'slug_en')
    op.add_column('product_translation', sa.Column('language_code_id', sa.Integer(), nullable=False))
    op.add_column('product_translation', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_translation_language_id_fkey'), 'product_translation', type_='foreignkey')
    op.create_foreign_key(None, 'product_translation', 'language_codes', ['language_code_id'], ['id'])
    op.create_foreign_key(None, 'product_translation', 'products', ['product_id'], ['id'])
    op.drop_column('product_translation', 'language_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_translation', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_translation', type_='foreignkey')
    op.drop_constraint(None, 'product_translation', type_='foreignkey')
    op.create_foreign_key(op.f('product_translation_language_id_fkey'), 'product_translation', 'language_codes', ['language_id'], ['id'])
    op.drop_column('product_translation', 'product_id')
    op.drop_column('product_translation', 'language_code_id')
    op.add_column('categories', sa.Column('slug_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('name_ro', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('slug_ro', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('categories_slug_ro_key'), 'categories', ['slug_ro'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_slug_en_key'), 'categories', ['slug_en'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_name_ro_key'), 'categories', ['name_ro'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_name_en_key'), 'categories', ['name_en'], postgresql_nulls_not_distinct=False)
    op.drop_table('category_translations')
    # ### end Alembic commands ###
