"""dsda

Revision ID: d775a77e05a3
Revises: 01582c439a78
Create Date: 2025-08-06 17:10:52.489009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd775a77e05a3'
down_revision: Union[str, Sequence[str], None] = '01582c439a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'slug_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'slug_ro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'slug_ro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'slug_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
