"""dsda

Revision ID: e73c59dfebee
Revises: 15b5b4d44069
Create Date: 2025-08-14 16:32:01.467927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e73c59dfebee"
down_revision: Union[str, Sequence[str], None] = "15b5b4d44069"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_specific_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("product_specification_id", sa.Integer(), nullable=False),
        sa.Column("language_code_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_code_id"],
            ["language_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_specification_id"],
            ["product_specifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_specific_translations")
    # ### end Alembic commands ###
