"""dsda

Revision ID: e81d92e24498
Revises: 8e877331b75f
Create Date: 2025-08-14 17:04:42.395269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e81d92e24498"
down_revision: Union[str, Sequence[str], None] = "8e877331b75f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_specifications", sa.Column("product_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_specifications", "product_id")
    # ### end Alembic commands ###
