"""dsda

Revision ID: fb1f416ba393
Revises: e81d92e24498
Create Date: 2025-08-14 18:12:10.811810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1f416ba393'
down_revision: Union[str, Sequence[str], None] = 'e81d92e24498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_description_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_name_slug_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('language_code_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('product_translation')
    op.add_column('product_extra_images', sa.Column('product_variant_id', sa.Integer(), nullable=True))
    op.alter_column('product_extra_images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'product_extra_images', 'product_variants', ['product_variant_id'], ['id'])
    op.add_column('product_variants', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_variants', sa.Column('image', sa.String(), nullable=True))
    op.add_column('product_variants', sa.Column('stock', sa.Integer(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('product_variants', 'stock')
    op.drop_column('product_variants', 'image')
    op.drop_column('product_variants', 'price')
    op.drop_constraint(None, 'product_extra_images', type_='foreignkey')
    op.alter_column('product_extra_images', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_extra_images', 'product_variant_id')
    op.create_table('product_translation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_code_id'], ['language_codes.id'], name=op.f('product_translation_language_code_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_translation_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_translation_pkey')),
    sa.UniqueConstraint('slug', name=op.f('product_translation_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('product_name_slug_translations')
    op.drop_table('product_description_translations')
    # ### end Alembic commands ###
