"""dsda

Revision ID: fb58aa1c6d90
Revises: 672a873b1521
Create Date: 2025-08-06 16:21:36.879851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb58aa1c6d90'
down_revision: Union[str, Sequence[str], None] = '672a873b1521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name_ro'])
    op.create_unique_constraint(None, 'categories', ['name_en'])
    op.create_unique_constraint(None, 'categories', ['slug_en'])
    op.create_unique_constraint(None, 'categories', ['slug_ro'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
