"""dsda

Revision ID: ff5ede6dea7d
Revises: 9dd85959dc34
Create Date: 2025-08-19 03:17:53.762316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5ede6dea7d'
down_revision: Union[str, Sequence[str], None] = '9dd85959dc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('name_en', sa.String(), nullable=False))
    op.add_column('product_variants', sa.Column('name_ro', sa.String(), nullable=False))
    op.alter_column('products', 'main_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'main_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('product_variants', 'name_ro')
    op.drop_column('product_variants', 'name_en')
    # ### end Alembic commands ###
