# Generated by Django 5.2.8 on 2025-11-08 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Romanian title')),
                ('meta_title_en', models.CharField(help_text='min: 10, max: 50', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='English meta title')),
                ('meta_title_ro', models.CharField(help_text='min: 10, max: 50', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Romanian meta title')),
                ('meta_description_en', models.TextField(help_text='min: 25, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='English meta description')),
                ('meta_description_ro', models.TextField(help_text='min: 25, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='Romanian meta description')),
                ('order', models.PositiveIntegerField(verbose_name='Order number')),
                ('slug', models.SlugField(help_text='min: 2, max: 25', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 2, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Romanian title')),
                ('order', models.PositiveIntegerField(verbose_name='Order number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'sub-category',
                'verbose_name_plural': 'sub-categories',
                'db_table': 'sub_categories',
            },
        ),
    ]
