# Generated by Django 5.2.8 on 2025-11-12 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, help_text='min: 2, max: 25', max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Slug'),
        ),
    ]
