# Generated by Django 5.2.8 on 2025-11-19 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], help_text='choices: INDIVIDUAL, COMPANY', verbose_name='Entity type')),
                ('email', models.EmailField(help_text='Email address', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(help_text='min: 2, max: 25', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First name')),
                ('last_name', models.CharField(help_text='min: 2, max: 25', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone number')),
                ('country', models.CharField(max_length=250, verbose_name='Country')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Postal code')),
                ('street', models.CharField(max_length=250, verbose_name='Street')),
                ('house_number', models.CharField(max_length=50, verbose_name='House number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
    ]
