# Generated by Django 5.2.8 on 2025-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DECLINED', 'Declined')], default='PENDING', verbose_name='Status'),
        ),
    ]
