# Generated by Django 5.2.8 on 2025-11-08 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 5, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 5, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Romanian title')),
                ('description_en', models.TextField(blank=True, help_text='min: 10, max: 2000', max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='English description')),
                ('description_ro', models.TextField(blank=True, help_text='min: 10, max: 2000', max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Romanian description')),
                ('slug', models.SlugField(help_text='min: 5, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Slug')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Forints', max_digits=10, null=True, verbose_name='Old price')),
                ('price', models.DecimalField(decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Forints', max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='accepted formats: png', upload_to='products/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(verbose_name='Order number')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'product-image',
                'verbose_name_plural': 'product-images',
                'db_table': 'product_images',
            },
        ),
    ]
