# Generated by Django 5.2.8 on 2025-11-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Stock count', verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, null=True, verbose_name='Old price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, verbose_name='Price'),
        ),
    ]
