# Generated by Django 5.2.8 on 2025-11-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
