# Generated by Django 5.2.8 on 2025-11-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, help_text='aspect: 3/4', upload_to='products/', verbose_name='Main image'),
            preserve_default=False,
        ),
    ]
