# Generated by Django 5.2.8 on 2025-11-09 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_title',
            field=models.CharField(blank=True, help_text='min: 5, max: 150', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Brand title'),
        ),
    ]
