# Generated by Django 5.2.8 on 2025-11-09 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 5, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 5, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Romanian title')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, null=True, verbose_name='Old price')),
                ('price', models.DecimalField(decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(help_text='Stock count', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'product-attribute-item',
                'verbose_name_plural': 'product-attribute-items',
                'db_table': 'product_attribute_items',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='min: 5, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='English title')),
                ('title_ro', models.CharField(help_text='min: 5, max: 30', max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Romanian title')),
                ('product', models.OneToOneField(help_text='product attribute', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'product-attribute',
                'verbose_name_plural': 'product-attributes',
                'db_table': 'product_attributes',
            },
        ),
    ]
