# Generated by Django 5.2.8 on 2025-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productattributeitem_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productattributeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='max_digits: 10, decimal_places: 2. Currency: Romanian Lei', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
