# Generated by Django 5.2.8 on 2025-11-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price_alter_productattributeitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeitem',
            name='attribute',
            field=models.ForeignKey(default=1, help_text='product attribute item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productattribute', verbose_name='Attribute Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.OneToOneField(help_text='product attribute', on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='products.product', verbose_name='Product'),
        ),
    ]
