# Generated by Django 5.2.8 on 2025-11-12 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productattributeitem_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, help_text='min: 5, max: 150', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Slug'),
        ),
    ]
